options:
  port:
    type: int
    default: 443
    description: The port to run the loadbalancer
  proxy_read_timeout:
    type: int
    default: 90
    description: The proxy_read_timeout nginx configuration value
  extra_sans:
    type: string
    default: ""
    description: |
      Space-separated list of extra SAN entries to add to the x509 certificate
      created for the load balancers.
